version: '3'
services:
  nginx:
    image: tqvthuworks/lab5-pictshare-nginx:latest
    ports:
      - '8080:80'
    networks:
      - pictshare
    # depends_on:
    #   - pictshare
    deploy:
      mode: global
      # replicas: 3
      restart_policy:
        condition: on-failure
  pictshare:
    image: ghcr.io/hascheksolutions/pictshare
    deploy: 
      mode: replicated
      replicas: 3
      resources:
        limits: 
          memory: 128M
    networks:
      - pictshare
    volumes:
      - images:/var/www/data
networks:
  pictshare:
    driver: overlay

volumes:
  images:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.92.30,nolock,rw,soft,nfsvers=3"
      device: ":/share-data"